/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#003527',
        'on-primary': '#ffffff',
        'primary-container': '#064e3b',
        'on-primary-container': '#80bea6',
        'inverse-primary': '#95d3ba',
        'primary-fixed': '#b0f0d6',
        'primary-fixed-dim': '#95d3ba',
        'on-primary-fixed': '#002117',
        'on-primary-fixed-variant': '#0b513d',
        'secondary': '#1b6b4f',
        'on-secondary': '#ffffff',
        'secondary-container': '#a6f2cf',
        'on-secondary-container': '#247155',
        'secondary-fixed': '#a6f2cf',
        'secondary-fixed-dim': '#8bd6b4',
        'on-secondary-fixed': '#002115',
        'on-secondary-fixed-variant': '#00513a',
        'tertiary': '#502000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#733100',
        'on-tertiary-container': '#ff985a',
        'tertiary-fixed': '#ffdbca',
        'tertiary-fixed-dim': '#ffb68e',
        'on-tertiary-fixed': '#331200',
        'on-tertiary-fixed-variant': '#763300',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface-variant': '#e1e3e4',
        'surface-tint': '#2b6954',
        'on-surface': '#191c1d',
        'on-surface-variant': '#404944',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'outline': '#707974',
        'outline-variant': '#bfc9c3',
        'background': '#f8f9fa',
        'on-background': '#191c1d',
      },
      fontFamily: {
        serif: ['"Source Serif 4"', 'serif'],
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        'unit': '8px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        'gutter': '24px',
        'section-gap': '80px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      boxShadow: {
        'organic': '0px 10px 30px rgba(6,78,59,0.05)',
        'organic-lg': '0px 20px 40px rgba(6,78,59,0.1)',
      },
      keyframes: {
        'soft-entrance': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'shimmer': {
          '0%': { transform: 'translate(-100%,-100%) rotate(45deg)' },
          '100%': { transform: 'translate(100%,100%) rotate(45deg)' },
        },
        'pulse-ring': {
          '0%': { boxShadow: '0 0 0 0 rgba(166,242,207,0.4)' },
          '70%': { boxShadow: '0 0 0 15px rgba(166,242,207,0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(166,242,207,0)' },
        },
        'cart-pop': {
          '50%': { transform: 'scale(1.4)' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'badge-bounce': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.25)' },
        },
      },
      animation: {
        'soft-entrance': 'soft-entrance 1.2s cubic-bezier(0.16,1,0.3,1) forwards',
        'shimmer': 'shimmer 6s infinite',
        'pulse-ring': 'pulse-ring 2s infinite',
        'cart-pop': 'cart-pop 0.4s cubic-bezier(0.175,0.885,0.32,1.275)',
        'fade-in-up': 'fade-in-up 0.8s ease-out forwards',
        'slide-in-right': 'slide-in-right 0.35s ease-out',
        'badge-bounce': 'badge-bounce 0.3s ease-out',
      },
    },
  },
  plugins: [],
};
